set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins'
set -g mouse on
set -g prefix C-r

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'


set -g @resurrect-dir '~/.local/share/tmux/resurrect'
set -g @resurrect-capture-pane-contents 'on'

set -g @continuum-save-interval '10'
set -g @continuum-restore 'on'

run '~/.local/share/tmux/plugins/tpm/tpm'